FROM langgenius/dify-api:1.14.2

USER root
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH=/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /buyerreach

COPY pyproject.toml ./
COPY app/__init__.py ./app/__init__.py
RUN pip install --no-cache-dir -e .

COPY app ./app
COPY migrations ./migrations
COPY alembic.ini ./alembic.ini
RUN chown -R 1001:1001 /buyerreach

ENTRYPOINT []
USER 1001
EXPOSE 8000
