from app.providers.errors import format_http_error
from app.providers.vendors import _is_transient_gateway_403


def test_html_gateway_error_is_replaced_with_actionable_message() -> None:
    message = format_http_error(403, "<html><body><h1>403 ERROR</h1>CloudFront</body></html>")

    assert "HTTP 403" in message
    assert "gateway rejected" in message
    assert "<html" not in message.lower()


def test_json_provider_error_retains_error_code_and_detail() -> None:
    message = format_http_error(400, '{"error_code":"INVALID_FILTERS","filter_error":"Unknown job title"}')

    assert message == "INVALID_FILTERS: Unknown job title"


def test_only_html_cloudfront_403_is_retryable() -> None:
    assert _is_transient_gateway_403(403, "<html><body>Generated by CloudFront</body></html>") is True
    assert _is_transient_gateway_403(403, '{"message":"forbidden"}') is False
