<template>
  <section class="outreach-page">
    <header class="page-header"><div><h1>邮件触达</h1><p>创建模板、选择已验证邮箱、设置多次发送时间，并通过审批后进入安全队列。</p></div><div class="actions"><el-button v-if="canAccounts" @click="accountOpen=true">配置发件邮箱</el-button><el-button v-if="canDraft" type="primary" @click="campaignOpen=true">创建发送活动</el-button></div></header>
    <el-alert type="warning" :closable="false"><template #title><b>当前发送状态：{{ activeAccount ? `已配置 ${activeAccount.from_email}` : '尚未配置发件邮箱，无法外发' }}</b>。回复、退订、退信或投诉会自动停止该邮箱后续邮件。</template></el-alert>
    <el-tabs v-model="tab"><el-tab-pane label="发送活动" name="campaigns"><el-empty v-if="!campaigns.length" description="暂无活动。先创建模板，再选择已验证邮箱创建活动。"/><el-table v-else :data="campaigns"><el-table-column prop="name" label="活动名称"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag>{{ label(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button v-if="canReview&&row.status==='draft'" link type="primary" @click="approve(row)">提交审批</el-button><el-button v-if="canSchedule&&row.status==='approved'" link type="success" @click="schedule(row)">加入发送队列</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="邮件模板" name="templates"><div class="tab-tools"><el-button v-if="canDraft" type="primary" @click="templateOpen=true">新建模板</el-button></div><el-empty v-if="!templates.length" description="暂无邮件模板"/><el-table v-else :data="templates"><el-table-column prop="name" label="名称"/><el-table-column prop="subject" label="主题"/><el-table-column prop="version" label="版本"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag type="info">草稿</el-tag></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="发件邮箱" name="accounts"><el-empty v-if="!accounts.length" description="尚未配置发件邮箱。配置后仍需在系统设置中完成服务商授权。"/><el-table v-else :data="accounts"><el-table-column prop="name" label="名称"/><el-table-column prop="from_email" label="发件邮箱"/><el-table-column prop="daily_limit" label="每日上限"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane></el-tabs>
    <el-dialog v-model="templateOpen" title="新建邮件模板" width="640px"><el-form label-position="top"><el-form-item label="模板名称"><el-input v-model="template.name" placeholder="例如：首次开发信"/></el-form-item><el-form-item label="邮件主题"><el-input v-model="template.subject" placeholder="例如：{{brand_name}} 合作咨询"/></el-form-item><el-form-item label="邮件正文"><el-input v-model="template.body_text" type="textarea" :rows="9" placeholder="支持纯文本；保存为草稿后可用于活动。"/></el-form-item></el-form><template #footer><el-button @click="templateOpen=false">取消</el-button><el-button type="primary" @click="saveTemplate">保存草稿</el-button></template></el-dialog>
    <el-dialog v-model="accountOpen" title="配置发件邮箱" width="560px"><el-alert type="info" :closable="false" title="保存后状态为“待配置”。请由管理员完成邮件服务商凭据与域名验证，系统才允许外发。"/><el-form label-position="top"><el-form-item label="账户名称"><el-input v-model="account.name"/></el-form-item><el-form-item label="发件邮箱"><el-input v-model="account.from_email"/></el-form-item><el-form-item label="显示名称"><el-input v-model="account.from_name"/></el-form-item><el-form-item label="每日发送上限"><el-input-number v-model="account.daily_limit" :min="1" :max="10000"/></el-form-item></el-form><template #footer><el-button @click="accountOpen=false">取消</el-button><el-button type="primary" @click="saveAccount">保存</el-button></template></el-dialog>
    <el-dialog v-model="campaignOpen" title="创建发送活动" width="720px"><el-steps :active="2" simple><el-step title="选择模板"/><el-step title="选择收件人"/><el-step title="设置时间"/></el-steps><el-form label-position="top" class="campaign-form"><el-form-item label="活动名称"><el-input v-model="campaign.name"/></el-form-item><el-form-item label="发件邮箱"><el-select v-model="campaign.sending_account_id" clearable placeholder="未配置时只可创建草稿"><el-option v-for="a in accounts" :key="a.id" :value="a.id" :label="`${a.name} · ${a.from_email}`"/></el-select></el-form-item><el-form-item label="收件人邮箱（每行一个，需来自数据中心）"><el-select v-model="campaign.email_ids" multiple filterable remote :remote-method="searchEmails" :loading="emailLoading" placeholder="搜索并选择已验证邮箱" style="width:100%"><el-option v-for="e in emailOptions" :key="e.id" :value="e.id" :label="e.address"/></el-select></el-form-item><el-form-item label="发送步骤"><div v-for="(step,i) in campaign.steps" :key="i" class="step"><el-select v-model="step.template_id" placeholder="选择模板"><el-option v-for="t in templates" :key="t.id" :value="t.id" :label="t.name"/></el-select><el-input-number v-model="step.delay_minutes" :min="0"/><span>分钟后发送</span><el-button link type="danger" :disabled="campaign.steps.length===1" @click="campaign.steps.splice(i,1)">删除</el-button></div><el-button link type="primary" @click="addStep">+ 添加后续发送时间点</el-button></el-form-item></el-form><template #footer><el-button @click="campaignOpen=false">取消</el-button><el-button type="primary" @click="saveCampaign">创建草稿</el-button></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'; import { ElMessage } from 'element-plus'; import { api } from '../api/client'; import { useAuth } from '../stores/auth'
const auth=useAuth(),tab=ref('campaigns'),templates=ref<any[]>([]),campaigns=ref<any[]>([]),accounts=ref<any[]>([]),emailOptions=ref<any[]>([]),emailLoading=ref(false),templateOpen=ref(false),accountOpen=ref(false),campaignOpen=ref(false)
const canDraft=computed(()=>auth.hasPermission('outreach:draft')),canReview=computed(()=>auth.hasPermission('outreach:review')),canSchedule=computed(()=>auth.hasPermission('outreach:schedule')),canAccounts=computed(()=>auth.hasPermission('outreach:manage_accounts')),activeAccount=computed(()=>accounts.value.find(a=>a.status==='active'))
const template=reactive({name:'',subject:'',body_text:''}),account=reactive({name:'',from_email:'',from_name:'',daily_limit:50}),campaign=reactive<any>({name:'',sending_account_id:null,email_ids:[],steps:[{template_id:null,delay_minutes:0}]})
const label=(s:string)=>({draft:'草稿',approved:'已审批',scheduled:'已进入队列',pending_configuration:'待服务商配置',active:'可发送'}[s]||s)
async function load(){const [t,c,a]=await Promise.all([api.get('/outreach/templates'),api.get('/outreach/campaigns'),api.get('/outreach/sending-accounts')]);templates.value=t.data.items||[];campaigns.value=c.data.items||[];accounts.value=a.data.items||[]}
async function searchEmails(q:string){if(!q)return;emailLoading.value=true;try{const r=await api.get('/emails',{params:{page_size:20,search:q}});emailOptions.value=r.data.items||[]}finally{emailLoading.value=false}}
async function saveTemplate(){if(!template.name||!template.subject||!template.body_text)return ElMessage.warning('请填写完整模板');await api.post('/outreach/templates',{...template,body_html:template.body_text.replaceAll('\n','<br>')});templateOpen.value=false;Object.assign(template,{name:'',subject:'',body_text:''});await load();ElMessage.success('模板已保存')}
async function saveAccount(){if(!account.name||!account.from_email)return ElMessage.warning('请填写账户名称和发件邮箱');await api.post('/outreach/sending-accounts',account);accountOpen.value=false;await load();ElMessage.success('已保存，等待服务商配置')}
function addStep(){campaign.steps.push({template_id:null,delay_minutes:24*60})}
async function saveCampaign(){if(!campaign.name||!campaign.email_ids.length||campaign.steps.some((s:any)=>!s.template_id))return ElMessage.warning('请填写活动名称、收件人和每个步骤的模板');await api.post('/outreach/campaigns',{...campaign,steps:campaign.steps.map((s:any,i:number)=>({...s,sequence_order:i+1}))});campaignOpen.value=false;Object.assign(campaign,{name:'',sending_account_id:null,email_ids:[],steps:[{template_id:null,delay_minutes:0}]});await load();ElMessage.success('活动草稿已创建')}
async function approve(r:any){await api.post(`/outreach/campaigns/${r.id}/approve`);await load();ElMessage.success('活动已审批')};async function schedule(r:any){const x=await api.post(`/outreach/campaigns/${r.id}/schedule`);await load();ElMessage.success(`已加入 ${x.data.scheduled} 封邮件队列`)};onMounted(load)
</script>
<style scoped>.outreach-page{display:grid;gap:18px}.page-header{display:flex;justify-content:space-between;gap:16px;align-items:start}.page-header h1{margin:0;font-size:28px}.page-header p{margin:8px 0;color:#64748b}.actions,.tab-tools{display:flex;gap:10px}.tab-tools{justify-content:flex-end;margin:0 0 12px}.campaign-form{margin-top:20px}.step{display:flex;gap:10px;align-items:center;margin-bottom:10px}.step .el-select{width:260px}@media(max-width:700px){.page-header,.step{align-items:stretch;flex-direction:column}.actions{justify-content:flex-start}.step .el-select{width:100%}}</style>
